### ISSUE TITLE
Nuget package installation fails

### ISSUE THREAD

**Issue by rivardjm** [clemensv/azure-servicebus-relay-samples#1]
There is a missing packages directory in the root of the project which prompts an initial error. Manually adding the packages directory resolves that error but then a new error is encountered. 

nuget.exe : Unable to find version '3.0' of package 'WindowsAzure.ServiceBus'.
At C:\azure-servicebus-relay-samples-master\scripts\azure\ServiceBus\GetServiceBusDll.ps1:21 char:12
- $install = & "$nugetExe" install WindowsAzure.ServiceBus -version 3.0 ...
-            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (Unable to find ...re.ServiceBus'.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

This error stems from the version of the nuget.exe in the tools/nuget directory. Updating to the latest version resolves the second issue.

**Comment by jtaubensee** [comment]
Please see our new service / samples repo, and refile if necessary: https://github.com/azure/azure-relay
